# Generated by Django 3.1.5 on 2021-01-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('progress', models.CharField(choices=[('неуд', 'неудовлетворительно'), ('уд', 'удовлетворительно'), ('хор', 'хорошо'), ('отл', 'отлично')], help_text='Успеваемость', max_length=4)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
